name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 — Récupère le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 — Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Étape 3 — Build et push de l'image
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: mon-app
          file: mon-app/Dockerfile
          push: true
          tags: gykey/mon-app:latest

      # Étape 4 — Redémarre Azure via Webhook
      - name: Restart Azure App Service
        run: |
          curl -X POST "${{ secrets.AZURE_WEBHOOK_URL }}"